repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-python-jose
        files: ^packages/plato-.*/src/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, vue, css, scss, json, yaml]
        additional_dependencies:
          - prettier@3.2.5
          - "@vue/eslint-config-prettier@8.0.0"
          - "@vue/eslint-config-typescript@12.0.0"

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
        # Run tests without generating coverage files during pre-commit
        args: ["-v", "--no-cov"]

      - id: frontend-test
        name: frontend-test
        entry: bash -c 'cd packages/plato-web && npm test'
        language: system
        pass_filenames: false
        files: ^packages/plato-web/.*\.(js|ts|vue)$
