version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/packages/plato-core/src:/app/packages/plato-api/src
      - PORT=8000
    volumes:
      - ./packages/plato-core/src:/app/packages/plato-core/src
      - ./packages/plato-api/src:/app/packages/plato-api/src
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./packages/plato-web/src:/app/src
      - ./packages/plato-web/public:/app/public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
