[project]
name = "plato-cli"
version = "0.1.0"
description = "CLI tool for Plato DevOps automation platform"
authors = []
dependencies = [
    "plato-core",  # Local dependency
    "typer~=0.9.0",
    "rich~=13.7.0",
]

[project.scripts]
plato = "plato_cli.main:app"

[project.optional-dependencies]
dev = [
    "pytest~=8.0.0",
    "pytest-cov~=4.1.0",
    "black~=24.1.0",
    "ruff~=0.2.1",
    "mypy~=1.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/plato_cli"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=plato_cli"

[tool.ruff]
select = ["E", "F", "I", "N", "W"]
ignore = []
line-length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
