[project]
name = "plato-api"
version = "0.1.0"
description = "REST API service for Plato DevOps automation platform"
authors = []
dependencies = [
    "plato-core",  # Local dependency
    "fastapi~=0.109.0",
    "uvicorn~=0.27.0",
    "python-jose[cryptography]~=3.3.0",
    "python-multipart~=0.0.9",
]

[project.optional-dependencies]
dev = [
    "pytest~=8.0.0",
    "pytest-cov~=4.1.0",
    "pytest-asyncio~=0.23.0",
    "httpx~=0.26.0",
    "black~=24.1.0",
    "ruff~=0.2.1",
    "mypy~=1.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/plato_api"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=plato_api"

[tool.ruff]
select = ["E", "F", "I", "N", "W"]
ignore = []
line-length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true 